apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/persistentvolumeclaim.yaml
  - the_project/manifests/configmap.yaml
  - the_project/manifests/deployment.yaml
  - the_project/manifests/service.yaml

images:
  - name: the_project
    newName: ssteevooh/the_project
    newTag: "3.5"
