apiVersion: v1
kind: ConfigMap
metadata:
  name: project-config
  namespace: project
data:
  PORT: "3000"
  IMAGE_FILE: "/usr/src/app/files/image.jpg"
  IMAGE_URL: "https://picsum.photos/1200"
  CACHE_TIME: "600000"
  TODO_BACKEND_HOST: "todo-backend-svc"
  TODO_BACKEND_PORT: "2345"
  TODO_BACKEND_PATH: "/todos"
