apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-todo-wiki-random
  namespace: project
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: wiki-todo
              image: ssteevooh/todo_backend:2.9
              command: ["node", "cronjob.js"]
              env:
                - name: TODO_BACKEND_HOST
                  value: todo-backend-svc
                - name: TODO_BACKEND_PORT
                  value: "2345"
                - name: TODO_BACKEND_PATH
                  value: /todos
          restartPolicy: OnFailure
