apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      volumes: # Define volume
        - name: shared-logs
          emptyDir: {}
      containers:
        - name: log-output-writer
          image: ssteevooh/log_output_writer:1.10
          volumeMounts: # Mount volume
            - name: shared-logs
              mountPath: /usr/src/app/files
        - name: log-output-reader
          image: ssteevooh/log_output_reader:1.10
          volumeMounts: # Mount volume
            - name: shared-logs
              mountPath: /usr/src/app/files